// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/App/AppButton.vue')['default']
    AppCard: typeof import('./src/components/App/AppCard.vue')['default']
    AppColorToggle: typeof import('./src/components/App/AppColorToggle.vue')['default']
    AppInput: typeof import('./src/components/App/AppInput.vue')['default']
    AppSelect: typeof import('./src/components/App/AppSelect.vue')['default']
    AppToggle: typeof import('./src/components/App/AppToggle.vue')['default']
    ICarbonUser: typeof import('~icons/carbon/user')['default']
    ILucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideBox: typeof import('~icons/lucide/box')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideCornerDownLeft: typeof import('~icons/lucide/corner-down-left')['default']
    ILucideCpu: typeof import('~icons/lucide/cpu')['default']
    ILucideEye: typeof import('~icons/lucide/eye')['default']
    ILucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    ILucideFlaskConical: typeof import('~icons/lucide/flask-conical')['default']
    ILucideInspect: typeof import('~icons/lucide/inspect')['default']
    ILucideKey: typeof import('~icons/lucide/key')['default']
    ILucideLayoutGrid: typeof import('~icons/lucide/layout-grid')['default']
    ILucideLayoutWrench: typeof import('~icons/lucide/layout-wrench')['default']
    ILucideLogOut: typeof import('~icons/lucide/log-out')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSettings2: typeof import('~icons/lucide/settings2')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    ILucideWrench: typeof import('~icons/lucide/wrench')['default']
    ITablerLock: typeof import('~icons/tabler/lock')['default']
    ITablerUser: typeof import('~icons/tabler/user')['default']
    LogoType: typeof import('./src/components/LogoType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav/SideNav.vue')['default']
    SideNavItem: typeof import('./src/components/SideNav/SideNavItem.vue')['default']
    TheFirmware: typeof import('./src/components/TheFirmware.vue')['default']
    ToolTip: typeof import('./src/components/ToolTip.vue')['default']
    UIButton: typeof import('./src/components/App/UIButton.vue')['default']
    UIInput: typeof import('./src/components/App/UIInput.vue')['default']
    UISelect: typeof import('./src/components/App/UISelect.vue')['default']
    UiSpinner: typeof import('./src/components/UI/UiSpinner.vue')['default']
    UiSteps: typeof import('./src/components/UI/UiSteps.vue')['default']
    UIToast: typeof import('./src/components/UI/UIToast.vue')['default']
  }
}

export {}
